#!/usr/bin/env bash

set -e

CONFIG_PREFIX="default"
CONFIG_SUFFIX=".conf.yaml"

CONFIG_DIR="profiles"
BACKUP_DIR="backups"
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

main() {
	backup_files "$@"
	run_dotbot "$@"
}

backup_files() {
	BACKUP_PATH="${BASE_DIR}/${BACKUP_DIR}"

	if [ ! -d "$BACKUP_PATH" ]; then
		echo "Creating backup directory at ${BACKUP_PATH}"
		mkdir -p "$BACKUP_PATH"
	else
		echo "Backup directory already exists, skipping creation..."
	fi

	for conf in $CONFIG_PREFIX $@; do
		CONFIG_FILE="${CONFIG_DIR}/${conf}${CONFIG_SUFFIX}"
		echo "Backing up files from ${CONFIG_FILE}..."

		while IFS=: read -r DEST FILE; do
			[[ "$DEST" =~ ^[[:space:]]*(~/|/.) ]] || continue

			DEST=$(echo "${DEST//\~/$HOME}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
			FILE=$(echo "$FILE" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')

			if [ -e "$DEST" ] && [ ! -L "$DEST" ]; then
				DIR_PATH=$(dirname "$FILE")

				if [ ! -d "${BACKUP_PATH}/${DIR_PATH}" ]; then
					mkdir -p "${BACKUP_PATH}/${DIR_PATH}"
				fi

				mv "${DEST}" "${BACKUP_PATH}/${FILE}"
				echo "Backed up ${DEST} to ${BACKUP_PATH}/${FILE}"
			fi
		done < <(awk "/^- link:/{p=1;next} /^-/{p=0} p{print}" "${BASE_DIR}/${CONFIG_FILE}")
	done
}

run_dotbot() {
	DOTBOT_DIR="dotbot"
	DOTBOT_BIN="bin/dotbot"

	cd "${BASE_DIR}"
	git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
	git submodule update --init --recursive "${DOTBOT_DIR}"

	for conf in $CONFIG_PREFIX $@; do
		"${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -c "${CONFIG_DIR}/${conf}${CONFIG_SUFFIX}"
	done
}

main "$@"