#!/usr/bin/env bash

set -e

BASE_CONFIG="default"
CONFIG_SUFFIX=".conf.yaml"

META_DIR="meta"
CONFIG_DIR="profiles"
BACKUP_DIR="backups"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASE_DIR}"
git -C "${BASE_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${BASE_DIR}"

META_PATH="${BASE_DIR}/${META_DIR}"

if [ $# -eq 0 ]; then
	"${META_PATH}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -c "${META_PATH}/${BASE_CONFIG}${CONFIG_SUFFIX}"
else
	for config in "$@"; do
		configFile="$(mktemp)"
		cat "${META_PATH}/${BASE_CONFIG}${CONFIG_SUFFIX}" "${META_PATH}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}" > "${configFile}"

		"${META_PATH}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -c "${configFile}"
		rm -f "$configFile"
	done
fi

BACKUP_PATH="${META_PATH}/${BACKUP_DIR}"

if [[ ! -d "$BACKUP_PATH" ]]; then
	echo "Creating backup directory at ${BACKUP_PATH}"
	mkdir -p "$BACKUP_PATH"
else
	echo "Backup directory already exists, skipping creation..."
fi

find "$HOME" -maxdepth 3 -type f -name '*.dotbot-backup.*' -not -path "${BACKUP_PATH}/*" | while read -r file; do
	FILE_NAME="$(basename "$file")"

	mv "$file" "${BACKUP_PATH}/${FILE_NAME}"
	echo "Moved ${file} to ${BACKUP_PATH}/${FILE_NAME}"
done
