# zmodload zsh/zprof

# Initialize XDG Directories
[ -d "${ZSH_STATE_HOME}" ] || mkdir -p "${ZSH_STATE_HOME}"
[ -d "${ZSH_CACHE_HOME}" ] || mkdir -p "${ZSH_CACHE_HOME}"

# Plugin Manager
if [[ ! -d "$ZINIT_HOME" ]]; then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

source "${ZINIT_HOME}/zinit.zsh"

# Plugins
zinit light-mode for \
	zdharma-continuum/fast-syntax-highlighting \
	zsh-users/zsh-completions \
	zsh-users/zsh-autosuggestions

# Keybinds
bindkey -e
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey '^H' backward-kill-word
bindkey '^[[3;5~' kill-word

# History
setopt inc_append_history
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Completion
zmodload zsh/complist

zstyle ':completion:*' menu select
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "${ZSH_CACHE_HOME}/zcompcache"
zstyle ':completion:*' completer _complete _files _correct _approximate
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors '${(s.:.)LS_COLORS}'

autoload -Uz compinit
compinit -u -d "${ZSH_CACHE_HOME}/zcompdump-$ZSH_VERSION"

# Theming
if command -v oh-my-posh > /dev/null 2>&1; then
	eval "$(oh-my-posh init zsh --config ~/.config/oh-my-posh/zhon12345.omp.json)"
fi

# FNM
if command -v fnm > /dev/null 2>&1; then
	eval "$(fnm env --use-on-cd --shell zsh)"
fi

# zprof