# zmodload zsh/zprof

# Global Aliases & Commands
[[ -f "${HOME}/.profile" ]] && \. ~/.profile

# Plugin Manager
if [[ "$MACHINE" = "Windows" ]]; then
	ZINIT_HOME="${HOME}/.zinit/bin"
else
	ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/bin"
fi

if [[ ! -d "${ZINIT_HOME}" ]]; then
  mkdir -p "$(dirname ${ZINIT_HOME})"
  git clone https://github.com/zdharma-continuum/zinit.git "${ZINIT_HOME}"
fi

source "${ZINIT_HOME}/zinit.zsh"

# Plugins
zinit light-mode for \
	zdharma-continuum/fast-syntax-highlighting \
	zsh-users/zsh-completions \
	zsh-users/zsh-autosuggestions

# Keybinds
bindkey -e
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey '^H' backward-kill-word
bindkey '^[[3;5~' kill-word

# History
HISTSIZE=5000
SAVEHIST=$HISTSIZE
HISTFILE="${XDG_CONFIG_HOME}/zsh/.zsh_history"
HISTDUP=erase

setopt inc_append_history
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors '${(s.:.)LS_COLORS}'

# Theming
if command -v oh-my-posh > /dev/null 2>&1; then
	eval "$(oh-my-posh init zsh --config ~/.config/oh-my-posh/zhon12345.omp.json)"
fi

# FNM
if command -v fnm > /dev/null 2>&1; then
	eval "$(fnm env --use-on-cd --shell zsh)"
fi

# zprof