
# Keybinds
bind '"\C-h": backward-kill-word'
bind '"\e[3;5~":kill-word'

# History
HISTSIZE=5000
HISTFILESIZE=$HISTSIZE
HISTFILE=~/.bash_history
HISTCONTROL=ignoreboth:erasedups

shopt -s histappend

HISTIGNORE='&:[ ]*'
PROMPT_COMMAND="history -a; history -n"

# Theming
if command -v oh-my-posh > /dev/null 2>&1; then
	eval "$(oh-my-posh init bash --config ~/.config/oh-my-posh/zhon12345.omp.json)"
fi

# FNM
if command -v fnm > /dev/null 2>&1; then
	eval "$(fnm env --use-on-cd --shell bash)"
fi